# Generated by Django 4.0.4 on 2022-05-19 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=200)),
                ('idp', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=200)),
                ('duracao', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicas.playlist')),
            ],
        ),
    ]
