# Generated by Django 4.0.4 on 2022-05-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='artista',
            field=models.CharField(default='nct', max_length=200),
            preserve_default=False,
        ),
    ]
