# Generated by Django 4.0.4 on 2022-05-08 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0002_musica_artista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='musica',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicas.playlist'),
        ),
    ]
