# Generated by Django 4.0.4 on 2022-05-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0004_musica_id_pesquisa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musica',
            old_name='id_pesquisa',
            new_name='idp',
        ),
    ]
