# Generated by Django 4.0.4 on 2022-05-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0005_rename_id_pesquisa_musica_idp'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='album',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musica',
            name='duracao',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musica',
            name='img',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musica',
            name='link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musica',
            name='idp',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
